import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

/**
 * Component 3: State Metadata Governance
 *
 * Manages versioning, changelogs, and automated roadmap extraction.
 */
export class ProtocolGovernance {
  constructor(private rootDir: string = path.join(__dirname, '../../../')) {}

  private run(command: string): string {
    try {
      return execSync(command, { cwd: this.rootDir, encoding: 'utf8' });
    } catch (err) {
      const error = err as { stderr?: string; message?: string };
      throw new Error(`Command failed: ${command}\n${error.stderr || error.message}`);
    }
  }

  /**
   * Bumps the patch version in VERSION.md and package.json.
   */
  async bumpVersion(): Promise<string> {
    const versionFile = path.join(this.rootDir, 'VERSION.md');
    const packageFile = path.join(this.rootDir, 'package.json');

    if (!fs.existsSync(versionFile)) {
      fs.writeFileSync(versionFile, '1.0.0');
    }

    const currentVersion = fs.readFileSync(versionFile, 'utf8').trim();
    const parts = currentVersion.split('.').map(Number);
    while (parts.length < 3) {
      parts.push(0);
    }
    if (parts[2] !== undefined) {
      parts[2]++;
    }
    const newVersion = parts.join('.');

    console.log(`[APEP] Bumping version: ${currentVersion} -> ${newVersion}`);
    fs.writeFileSync(versionFile, newVersion);

    const pkg = JSON.parse(fs.readFileSync(packageFile, 'utf8'));
    pkg.version = newVersion;
    fs.writeFileSync(packageFile, JSON.stringify(pkg, null, 2));

    return newVersion;
  }

  /**
   * Updates TODO.md and ROADMAP.md based on codebase scanning.
   */
  async syncRoadmap(): Promise<void> {
    console.log('[APEP] Extracting roadmap from codebase...');
    const todoFile = path.join(this.rootDir, 'TODO.md');

    try {
      // Use grep to find todos
      const findings = this.run('grep -rE "TODO|FIXME" src/ --exclude-dir=node_modules || echo ""');
      if (findings) {
        let content = '# AUTOMATED TODO LIST\n\nGenerated by APEP Governance\n\n';
        findings.split('\n').forEach(line => {
          if (line.trim()) {
            content += `- [ ] ${line.trim()}\n`;
          }
        });
        fs.writeFileSync(todoFile, content);
        console.log('✓ TODO.md synchronized.');
      }
    } catch (err) {
      console.warn('[!] Roadmap extraction failed.');
    }
  }

  /**
   * Updates CHANGELOG.md with the latest version entry.
   */
  async updateChangelog(version: string): Promise<void> {
    const changelogFile = path.join(this.rootDir, 'CHANGELOG.md');
    if (!fs.existsSync(changelogFile)) return;

    const date = new Date().toISOString().split('T')[0];
    const entry = `\n## [${version}] - ${date}\n### Added\n- Automated Protocol Sync and Branch Reconciliation.\n`;

    let content = fs.readFileSync(changelogFile, 'utf8');
    if (content.includes('## [Unreleased]')) {
       content = content.replace('## [Unreleased]', `## [Unreleased]\n${entry}`);
    } else {
       content = `## [${version}] - ${date}${entry}\n` + content;
    }
    fs.writeFileSync(changelogFile, content);
    console.log('✓ CHANGELOG.md updated.');
  }

  /**
   * Execution logic for governance metadata.
   */
  async execute(): Promise<void> {
    const newVersion = await this.bumpVersion();
    await this.syncRoadmap();
    await this.updateChangelog(newVersion);
  }
}
