import { Store } from '../models/Store';
import { Proposal } from '../models/types';
import { globalTriage } from './triage';
import { randomUUID } from 'crypto';

/**
 * AI-Driven Autonomous Proposal Generator
 *
 * Generates automated proposals based on system trends, unused treasury funds,
 * and high-activity subjects without human intervention.
 */
export class AutonomousProposalGenerator {
  constructor(private store: Store) {}

  /**
   * Generates a new proposal based on system trends or unused funds.
   */
  generateAutonomousProposal(): Proposal | null {
    const trends = this.store.getHistoricalTrends();
    if (trends.length === 0) return null;

    // Get the most recent trend
    const latestTrend = trends[trends.length - 1];

    // Look for high activity subjects
    const subjects = this.store.getHighActivitySubjects(5);

    if (subjects.length === 0) {
       // Generate a general platform improvement proposal
       return this.createProposal(
         'Platform General Improvement Initiative',
         'An automated initiative to improve the overall platform stability based on recent governance cycles.',
         'General',
         5000
       );
    }

    const targetSubject = subjects[0];

    return this.createProposal(
       `Automated Initiative: ${targetSubject} Expansion`,
       `This is an autonomously generated proposal to expand efforts in ${targetSubject} based on recent high citizen engagement.`,
       targetSubject || 'General',
       10000
    );
  }

  private createProposal(title: string, abstract: string, subject: string, budget: number): Proposal {
     const id = `auto-prop-${Date.now()}`;
     const committees = this.store.getCommittees();

     // Find or default committee
     let committeeMatch = globalTriage.suggestCommittee(title, abstract, committees);

     const proposal: Proposal = {
        id,
        title,
        abstract,
        detailedSpecs: `This proposal was autonomously generated by the LiquidGov AI Generator responding to system engagement in ${subject}.`,
        proposerId: 'system-ai-generator',
        committeeId: (committeeMatch && committeeMatch.id) ? committeeMatch.id : 'General-Committee',
        status: 'DRAFT',
        milestones: [
           { id: 'm1', description: 'Initial Planning', targetBudget: budget * 0.2, isCompleted: false },
           { id: 'm2', description: 'Execution', targetBudget: budget * 0.8, isCompleted: false }
        ],
        totalTargetBudget: budget,
        currentFunding: 0,
        tokenSymbol: 'USD',
        votesFor: 0,
        votesAgainst: 0,
        executionPayload: JSON.stringify({ action: 'EXPAND_INITIATIVE', subject })
     };

     return proposal;
  }
}
